#!/usr/bin/env bash
cfactor()
{
	if [ $# -ne 3 ];
        then
                arg=("$@")
                c=0
                num_2=1
                for j in ${arg[*]};
                do
                        if [ $c -gt 1 ];
                        then
                                num_2=$(echo $j*$num_2 | bc)
                        fi
                        c=$((c + 1))
                done
        else
                num_2=$3
        fi

        num_1=$2
        num=$(echo "$1" | tr ':' '=')

        res=$(echo "if($num_2 > $num_1) 1 else 0" | bc)
	        if ((res == 1)); then
		        num_cp=$num_1
		        num_1=$num_2
		        num_2=$num_cp
                fi

        echo "$num$num_1*$num_2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                res=$(factor "$i")
                cfactor $res

        done < "$1"
fi
